version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: healthcare
      POSTGRES_USER: healthcare_user
      POSTGRES_PASSWORD: healthcare_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    command: |
      bash -c "pipenv run python manage.py migrate --noinput && pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./healthcarebackend:/app/healthcarebackend  # Bind mount the app directory
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://healthcare_user:healthcare_pass@db:5432/healthcare
      - DEBUG=True

volumes:
  db_data:
